export const titles = [
	// --- Top 10: Always Important ---
	{ name: 'Frontend Developer', isImportant: true },
	{ name: 'React Developer', isImportant: true },
	{ name: 'Next.js Developer', isImportant: true },
	{ name: 'Three.js Specialist', isImportant: true },
	{ name: 'Creative Coder', isImportant: true },
	{ name: 'JavaScript Expert', isImportant: true },
	{ name: 'React Master', isImportant: true },
	{ name: 'WebGL Explorer', isImportant: true },
	{ name: 'Git Guru', isImportant: true },
	{ name: 'WebGPU Wizard', isImportant: true },

	// --- Creative / Technical (40) ---
	{ name: 'UI Magician', isImportant: false },
	{ name: 'Canvas Bender', isImportant: false },
	{ name: 'Real-Time Renderer', isImportant: false },
	{ name: 'DOM Sculptor', isImportant: false },
	{ name: 'Pixel Pusher', isImportant: false },
	{ name: '3D Web Crafter', isImportant: false },
	{ name: 'Motion Maker', isImportant: false },
	{ name: 'Logic Layer Lover', isImportant: false },
	{ name: 'State Wrangler', isImportant: false },
	{ name: 'Shady Shader Dev', isImportant: false },
	{ name: 'Geometry Wrangler', isImportant: false },
	{ name: 'GPU Optimizer', isImportant: false },
	{ name: 'Component Builder', isImportant: false },
	{ name: 'Vertex Whisperer', isImportant: false },
	{ name: 'Web Animator', isImportant: false },
	{ name: 'Shader Alchemist', isImportant: false },
	{ name: 'Data Flow Hacker', isImportant: false },
	{ name: 'React Router Rider', isImportant: false },
	{ name: 'Frame Chaser', isImportant: false },
	{ name: 'Dynamic Layout Dev', isImportant: false },
	{ name: 'WebGL Innovator', isImportant: false },
	{ name: 'Render Pipeline Pilot', isImportant: false },
	{ name: 'Concurrency Crafter', isImportant: false },
	{ name: 'UX Engineer', isImportant: false },
	{ name: 'Visual Explorer', isImportant: false },
	{ name: 'Virtual World Coder', isImportant: false },
	{ name: 'Code Canvas Artist', isImportant: false },
	{ name: 'Three.js Tinkerer', isImportant: false },
	{ name: 'Scene Composer', isImportant: false },
	{ name: 'Motion Architect', isImportant: false },
	{ name: 'Voxel Explorer', isImportant: false },
	{ name: 'Texture Wrangler', isImportant: false },
	{ name: 'Performance Tweaker', isImportant: false },
	{ name: 'REST API Integrator', isImportant: false },
	{ name: 'Layout Strategist', isImportant: false },
	{ name: 'UX Flow Builder', isImportant: false },
	{ name: 'Pattern Explorer', isImportant: false },
	{ name: 'Web Interactivity Engineer', isImportant: false },
	{ name: 'Frontend Flow Master', isImportant: false },
	{ name: 'Shader Surgeon', isImportant: false },

	// --- Playful / Fun (20) ---
	{ name: 'Tailwind Enjoyer™', isImportant: false },
	{ name: 'CSS Summoner', isImportant: false },
	{ name: 'Clicky Thing Maker', isImportant: false },
	{ name: 'Browser Whisperer', isImportant: false },
	{ name: 'GPU Enthusiast', isImportant: false },
	{ name: 'One-Dev Army', isImportant: false },
	{ name: 'JavaScript Gym Rat', isImportant: false },
	{ name: 'Scroll Sorcerer', isImportant: false },
	{ name: 'Visual Hacker', isImportant: false },
	{ name: 'Web Wizard', isImportant: false },
	{ name: 'DOM Hacker', isImportant: false },
	{ name: 'Component Conjurer', isImportant: false },
	{ name: 'Bug Squasher', isImportant: false },
	{ name: 'Code Wrangler', isImportant: false },
	{ name: 'State Sorcerer', isImportant: false },
	{ name: 'Pixel Prophet', isImportant: false },
	{ name: 'Button Click Enabler', isImportant: false },
	{ name: 'Promise Ninja', isImportant: false },
	{ name: 'Lazy Loading Lord', isImportant: false },
	{ name: 'CSS Spellcaster', isImportant: false },

	// --- Personal / Quirky (20) ---
	{ name: 'Minecraft Addict', isImportant: false },
	{ name: 'Passionate Apashe Listener', isImportant: false },
	{ name: 'Gym-Then-Code Dev', isImportant: false },
	{ name: 'Music-and-Markup Maker', isImportant: false },
	{ name: 'Debug-and-Deadlift Dev', isImportant: false },
	{ name: 'Controller-to-Keyboard Convert', isImportant: false },
	{ name: 'Beats-and-Bundlers Buff', isImportant: false },
	{ name: 'Code-Gym-Repeat Dev', isImportant: false },
	{ name: 'Keyboard-and-Creatine Coder', isImportant: false },
	{ name: 'Late Night Builder', isImportant: false },
	{ name: 'Sleepless Shader Dev', isImportant: false },
	{ name: 'Caffeine Addict', isImportant: false },
	{ name: 'Chunk Loader', isImportant: false },
	{ name: 'Diablo IV Enthusiast', isImportant: false },
	{ name: 'Raytracing Fan', isImportant: false },
	{ name: 'Passionate Indie Game Enjoyer', isImportant: false },
	{ name: 'Minecraft Builder', isImportant: false },
	{ name: 'Synthwave Coder', isImportant: false },
	{ name: 'Motion-and-Music Maker', isImportant: false },
	{ name: 'Night-Owl Coder', isImportant: false }
];
